made check config variables are specified

diff --git a/k8s-deploy b/k8s-deploy
--- a/k8s-deploy
+++ b/k8s-deploy
@@ -150,6 +150,12 @@ if [[ "$stage_docker" == "true" ]]; then
 	echo "# Deploying Docker image #"
 	echo "##########################"
 
+	# Check required configuration variables are set
+	if [ -z "$DOCKER_REPO" ]; then
+		echo "Error: docker stage requires the DOCKER_REPO environment variable to be set" >&2
+		exit 1
+	fi
+
 	# Build docker image tag
 	version=$(git rev-parse --verify HEAD)
 	if [[ "$?" != "0" ]]; then
@@ -185,6 +191,12 @@ if [[ "$stage_deploy" == "true" || "$stage_rm_deploy" == "true" ]]; then
 	echo "#########################"
 	echo "# Deploying Helm charts #"
 	echo "#########################"
+
+	# Check required configuration variables are set
+	if [ -z "$DEPLOY_DIR" ]; then
+		echo "Error: deploy / rm-deploy stage requires the DEPLOY_DIR environment variable to be set" >&2
+		exit 1
+	fi
 
 	# Helm packages
 	for pkg in $(find "$DEPLOY_DIR" -mindepth 1 -maxdepth 1 -type d); do
